apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-a-vs
  namespace: mesh-demo
spec:
  hosts:
  - "*"
  gateways:
  - mesh-gateway   # ✅ ONLY THIS

  http:
  - match:
    - uri:
        prefix: "/v2"
    route:
    - destination:
        host: service-a
        subset: v2
      weight: 100

  - match:
    - uri:
        prefix: "/api"
    route:
    - destination:
        host: service-a
        subset: v1
      weight: 80
    - destination:
        host: service-a
        subset: v2
      weight: 20

  - route:
    - destination:
        host: service-a
        subset: v1